import type { IconType } from "react-icons";
import {
  SiBootstrap,
  SiCss,
  SiCplusplus,
  SiDart,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGo,
  SiGraphql,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiKotlin,
  SiLaravel,
  SiMui,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpencv,
  SiPandas,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiReact,
  SiRedis,
  SiRust,
  SiSass,
  SiScikitlearn,
  SiShadcnui,
  SiSocketdotio,
  SiSpring,
  SiSpringboot,
  SiSupabase,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVercel,
  SiVuedotjs,
} from "react-icons/si";
import { FaCube, FaGithub, FaLinkedinIn } from "react-icons/fa";
import { FiMail } from "react-icons/fi";

/**
 * Icon keys used by src/data/profile.ts (`techGroups[].icon`) and the
 * hero social buttons. To add a new tech: import its icon from
 * react-icons/si (https://react-icons.github.io/icons?name=si) and add a
 * line here, then reference the key in profile.ts.
 */
export const TECH_ICONS: Record<string, IconType> = {
  cplusplus: SiCplusplus,
  nextjs: SiNextdotjs,
  react: SiReact,
  nodejs: SiNodedotjs,
  typescript: SiTypescript,
  javascript: SiJavascript,
  express: SiExpress,
  fastify: SiExpress, // no dedicated Fastify glyph in react-icons 5.x
  python: SiPython,
  django: SiDjango,
  flask: SiFlask,
  tailwind: SiTailwindcss,
  shadcnui: SiShadcnui,
  mui: SiMui,
  bootstrap: SiBootstrap,
  sass: SiSass,
  framer: SiFramer,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,
  prisma: SiPrisma,
  graphql: SiGraphql,
  supabase: SiSupabase,
  firebase: SiFirebase,
  docker: SiDocker,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  vercel: SiVercel,
  netlify: SiNetlify,
  figma: SiFigma,
  postman: SiPostman,
  nestjs: SiNestjs,
  spring: SiSpring,
  springboot: SiSpringboot,
  php: SiPhp,
  laravel: SiLaravel,
  kotlin: SiKotlin,
  swift: SiSwift,
  go: SiGo,
  rust: SiRust,
  socketio: SiSocketdotio,
  pandas: SiPandas,
  numpy: SiNumpy,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  scikitlearn: SiScikitlearn,
  opencv: SiOpencv,
  huggingface: SiHuggingface,
  html5: SiHtml5,
  css3: SiCss,
  vue: SiVuedotjs,
  // hero social buttons resolve through the same map
  linkedin: FaLinkedinIn,
  email: FiMail,
};

/** Icons for the hero's social buttons. */
export const SOCIAL_ICONS = {
  github: FaGithub,
  linkedin: FaLinkedinIn,
  email: FiMail,
} as const;

/** Generic fallback so a mistyped icon key is visible instead of blank. */
export const FALLBACK_ICON: IconType = FaCube;
